# Generated by Django 3.0 on 2022-05-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220504_1623'),
    ]

    # renamed operations
    state_operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),


        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
